<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>scanar_diagnostics_dashboard</name>
  <version>3.15.0</version>
  <description>ScanAR Diagnostics and Engineering Development Dashboard package</description>
  <maintainer email="scanarstereo@todo.todo">scanarstereo</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>cmake</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>scanar_interfaces</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
