<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>elp_camera_driver</name>
  <version>1.5.0</version>
  <description>ELP 5MP Global Shutter USB Camera ROS 2 Driver for ScanAR C</description>
  <maintainer email="scanar@viture.com">scanar</maintainer>
  <license>Proprietary</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
